apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  labels:
    run: nginx-nodeport-service
spec:
  type: NodePort     # 서비스 타입
  ports:
  - port: 80       # 서비스 포트
    targetPort: 80   # 타켓, 즉 pod의 포트
    protocol: TCP
    nodePort: 31000
    name: http
  selector:
    app: nginx